interface util {
	record delims {
		reasoning: option<tuple<string, string>>,
		tool-call: tuple<string, string>,
	}

	record response {
		reasoning: option<string>,
		content: string,
		tool-calls: list<tool-call>,
	}

	record tool-call {
		name: string,
		arguments: list<tuple<string, string>>,
	}
}

world parser {
	use util.{delims, response};
	export parse: func(response: string, delims: option<delims>) -> response;
}
