interface tools {
	use types.{message, tool};

	record tool-response {
		output: string,
		score: f64,
	}

	call-tool: func(tool-name: string, args: list<tuple<string, string>>) -> tool-response;
	get-tools: func() -> list<tool>;
}
